version: "3.6"

services:

  node-server:
    build: ./server
    image: dank-node
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    container_name: node-server
    environment:
      mode: dev

  react-server-dev:
    build: ./client
    image: dank-react
    volumes:
      - ./client:/ui
    ports:
      - 3000:3000
    container_name: react-server-dev
    environment:
      mode: dev

  redis:
    image: redis
    container_name: redis-dev
    ports:
      - 6379:6379

  postgres-db:
    build: ./postgreSQL
    image: dank-postgres
    container_name: postgres-dev
    volumes:
      - ./postgreSQL/pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dankPassword
      POSTGRES_USER: dankAdmin
      POSTGRES_DB: testDB

